@startuml

title Поиск ответов на вопросы по базе знаний

actor User
User --> [TelegramBot]

package "Облако" <<Облако>> {
  [TelegramBot] --> [CLOUD:retriever-service]
  [CLOUD:retriever-service] --> [Store] : вектора
  [CLOUD:retriever-service] --> [CLOUD:squad-service]
  [CLOUD:squad-service] --> [RuBERT-Squad]
  [RuBERT-Squad] --> [CLOUD:squad-service]
  [CLOUD:squad-service] --> [CLOUD:retriever-service]
  [CLOUD:retriever-service] --> [TelegramBot] 
}

[TelegramBot] --> User
@enduml